### PR TITLE
Delivered Homework-3!

### PR DESCRIPTION
**Pull request by efantinatti**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
A: Improved the code and delivered an extra.

## What did you learn from the changes you have made?
A: A lot of things.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
A: No.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
A: A lot of them, specially for subqueries.

## How were these changes tested?
A: Via DB SQLIte.

## A reference to a related issue in your repository (if applicable)
A: o.

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by amanda-ng518 — APPROVED** [review]
HW3: good
AGGREGATE Q2 may use LEFT JOIN
8/8

**Review by amanda-ng518 — APPROVED** [review]
HW4: good, awaiting UNION SQL to be done in HW5
8/8

**Comment by efantinatti** [comment]
Thanks Amanda for your revision. I'll check the HW-5 out.

**Comment by efantinatti** [comment]
Hi Amanda, I was reading your email and understood my HW4 is 8/8 but you said it is missing UNION for HW5, but the UNION is in the HW4 which was done. HW5 doesn’t mention anything about it.




[8:11](https://uoft-dsi-certificates.slack.com/archives/D073U8FA9HU/p1716592275845439)
But the UNION is in the HW4 which was done. HW5 doesn’t mention anything about it.

**Comment by amanda-ng518** [comment]
HW4: good
8/8

**Comment by efantinatti** [comment]
Delivered my HW6!

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
HW5: 8/8

INSERT Q2
INSERT INTO product_units (product_id, product_name,
  product_size, product_category_id, product_qty_type, snapshot_timestamp)
      SELECT
          product_id,
          product_name,
          product_size,
          product_category_id,
          product_qty_type,
          CURRENT_TIMESTAMP
      FROM product AS p
      WHERE product_id = 7

DELETE Q1
WITH older_record AS
(SELECT product_id
		,MIN(snapshot_timestamp) AS snapshot_timestamp
		FROM product_units 
		WHERE product_id = 7)
DELETE FROM product_units
WHERE (product_id = 
	(SELECT  product_id 
	FROM older_record
		)
AND snapshot_timestamp = 	
	(SELECT  snapshot_timestamp 
	FROM older_record
		))

UPDATE Q1
ALTER TABLE product_units
ADD current_quantity INT;
UPDATE product_units
SET current_quantity = (
	SELECT current_quantity 
	FROM (
		SELECT  p.product_id, COALESCE(quantity,0) as current_quantity
		FROM product_units p
		LEFT JOIN (
			SELECT *
			,ROW_NUMBER() OVER( PARTITION BY vi.product_id ORDER BY market_date DESC) AS rn
			FROM vendor_inventory vi 
		) vi ON p.product_id  = vi.product_id
		WHERE rn = 1 
		OR rn IS NULL
	) p
WHERE product_units.product_id = p.product_id);

**Review by amanda-ng518 — APPROVED** [review]
HW6: 8/8

**Comment by efantinatti** [comment]
Hi Amanda

Delete is not missing there.

It is answered for all the required questions.

**Comment by efantinatti** [comment]
Added the Assignment 1

**Pull request closed without merging**
