### PR TITLE
Homeworks

### PR DESCRIPTION
**Pull request by efantinatti**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
A: Answeting homework-1 and homework-2.

## What did you learn from the changes you have made?
A: a lot!

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
A: Using sqlite3 pure command line!

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
A: No

## How were these changes tested?
A: Using the GUI version of sqlite.

## A reference to a related issue in your repository (if applicable)
A: n/a

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
Hi there, your HW1 is missing

**Comment by efantinatti** [comment]
Hi Amanda

It is there!

https://github.com/efantinatti/sql/blob/Homeworks/03_homework/homework_1.md

**Review by amanda-ng518 — APPROVED** [review]
HW1: good job, 8/8

**Review by amanda-ng518 — APPROVED** [review]
HW2:
Join Q1 missing "ORDER BY", swapped files for FROM and INNER JOIN
7/8

**Pull request merged**
